export * from './WhatsAppIcon'
export * from './TelegramIcon'
export * from './ArrowRightIcon'
export * from './InstagramIcon'
export * from './LogoIcon'
export * from './GrowStatisticIcon'
export * from './TelegramV2Icon'